<?php
// These stubs were generated by the phan stub generator.
// @phan-stub-for-extension ddtrace@0.60.0

namespace DDTrace {
    class SpanData {
        public $name;
        public $type;
        public $service;
        public $resource;
    }

    class Type {
        const WEB_SERVLET = 'web_servlet';
    }

    function trace_method() {}
}
