/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/donation-form': {
    get: {
      responses: {
        /** @description success */
        200: {
          content: {
            'application/json': components['schemas']['DonationFormResource']
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    DonationFormResource: {
      id: string
      name: string
      template: string
      layout: string
      isDefaultForm: boolean
      brandingLogo: {
        createdAt?: string
        full: string
        id: string
        isAudio?: boolean
        isImage?: boolean
        isVideo?: boolean
        thumb?: string
        updatedAt?: string
      }
      brandingMonthlyLogo: {
        createdAt?: string
        full: string
        id: string
        isAudio?: boolean
        isImage?: boolean
        isVideo?: boolean
        thumb?: string
        updatedAt?: string
      }
      brandingColour: string
      backgroundImage: {
        createdAt?: string
        full?: string
        id?: string
        isAudio?: boolean
        isImage?: boolean
        isVideo?: boolean
        thumb?: string
        updatedAt?: string
      }
      landingPageHeadline: string
      landingPageDescription: string
      billingPeriods: string
      defaultAmountType?: string
      defaultAmountValue: number
      defaultAmountValues: number[]
      badgesEnabled?: boolean
      socialProofEnabled: boolean
      socialProofPrivacy?: string
      transparencyPromiseEnabled: boolean
      transparencyPromiseType: string
      transparencyPromise1Percentage?: number
      transparencyPromise1Description?: string
      transparencyPromise2Percentage?: number
      transparencyPromise2Description?: string
      transparencyPromiseStatement?: string
      emailOptinDescription: string
      emailOptinNagMessage?: string | null
      emailOptinEnabled: boolean
      upsellEnabled: boolean
      upsellHeading?: string | null
      upsellDescription: string
      upsellConfirmation?: string | null
      socialLinkTitle?: string
      socialLinkDescription?: string
      socialPreviewImage: {
        createdAt?: string
        full?: string
        custom?: {
          socialPreview?: string
        }
        id?: string
        isAudio?: boolean
        isImage?: boolean
        isVideo?: boolean
        thumb?: string
        updatedAt?: string
      }
      doubleTheDonationConnected?: boolean
      doubleTheDonationEnabled?: boolean
      thankYouOnscreenMessage?: string
      thankYouOnscreenMonthlyMessage?: string | null
      thankYouEmailMessage: string
      thankYouEmailMonthlyMessage?: string | null
      navigationFooterCtaEnabled?: boolean
      navigationFooterCtaLabel?: string | null
      navigationFooterCtaLink?: string | null
      exitConfirmationDescription: string
      requireBillingAddress?: boolean
      gtmContainerId?: string
      metaPixelId?: string
      dpEnabled?: boolean
      dpGlCode?: string
      dpCampaign?: string
      dpSolicitCode?: string
      dpSubSolicitCode?: string
      dpMeta9?: string
      dpMeta10?: string
      dpMeta11?: string
      dpMeta12?: string
      dpMeta13?: string
      dpMeta14?: string
      dpMeta15?: string
      dpMeta16?: string
      dpMeta17?: string
      dpMeta18?: string
      dpMeta19?: string
      dpMeta20?: string
      dpMeta21?: string
      dpMeta22?: string
      embedOptionsReminderEnabled?: boolean
      embedOptionsReminderDescription: string
      embedOptionsReminderBackgroundColour?: string
      embedOptionsReminderPosition?: string
      isTaxReceiptable?: boolean
      publicUrl?: string
      shortlinkUrl?: string
      previewImageUrl?: string
      testmodeUrl?: string
      stats?: {
        donorCount?: number
        revenueAmount?: number
        conversion?: number
        currency?: string
        views?: number
        trends?: {
          revenues?: {
            data?: {
              /** Format: date */
              date?: string
            }
          }
          views?: {
            data?: {
              /** Format: date */
              date?: string
            }
          }
          donors?: {
            trend?: number
            previousPeriod?: number
            lastPeriod?: number
          }
          conversions?: {
            trend?: number
            previousPeriod?: number
            lastPeriod?: number
          }
        }
      }
      qrCode?: string
      createdBy?: string
      createdAt?: string
      updatedAt?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export type operations = Record<string, never>
