export { Dialog } from './Dialog'
export { DialogHeader } from './DialogHeader'
export { DialogFooter } from './DialogFooter'
export { DialogContent } from './DialogContent'
export type { DialogProps } from './Dialog'
