import {
  faBookOpen,
  faBell,
  faChartBar,
  faChevronDown,
  faChild,
  faCog,
  faCommentAltDots,
  faDesktop,
  faEnvelopeOpen,
  faExternalLink,
  faFileInvoiceDollar,
  faFlagCheckered,
  faGlobeAmericas,
  faGripHorizontal,
  faHandHoldingUsd,
  faHeart,
  faHome,
  faIdCardAlt,
  faMoneyCheckAlt,
  faPlug,
  faPlus,
  faPlusCircle,
  faShoppingCart,
  faSignalStream,
  faThermometerThreeQuarters,
  faTicket,
  faUserFriends,
  faUserHeadset,
  faUserCircle,
  faUser,
  faSignOut,
} from '@fortawesome/pro-regular-svg-icons'

export const ICONS = {
  'sign-out': faSignOut,
  user: faUser,
  'book-open': faBookOpen,
  'user-circle': faUserCircle,
  bell: faBell,
  'plus-circle': faPlusCircle,
  'chevron-down': faChevronDown,
  'external-link': faExternalLink,
  plus: faPlus,
  'grip-horizontal': faGripHorizontal,
  'hand-holding-usd': faHandHoldingUsd,
  'file-invoice-dollar': faFileInvoiceDollar,
  desktop: faDesktop,
  'id-card-alt': faIdCardAlt,
  'user-friends': faUserFriends,
  'flag-checkered': faFlagCheckered,
  'money-check-alt': faMoneyCheckAlt,
  ticket: faTicket,
  'shopping-cart': faShoppingCart,
  home: faHome,
  child: faChild,
  heart: faHeart,
  'comment-alt-dots': faCommentAltDots,
  'signal-stream': faSignalStream,
  'globe-americas': faGlobeAmericas,
  'thermometer-three-quarters': faThermometerThreeQuarters,
  'envelope-open': faEnvelopeOpen,
  'chart-bar': faChartBar,
  cog: faCog,
  plug: faPlug,
  'user-headset': faUserHeadset,
}
