export const supportedPrimaryColors = {
  green: {
    bgColor: 'bg-green-600',
    bgColorLight: 'bg-green-500',
    bgColorPale: 'bg-green-100',
    hoverBgColorLight: 'hover:bg-green-500',
    activeBgColorDark: 'active:bg-green-700',
    borderColor: 'border-green-600',
    textColor: 'text-green-600',
    focusBorderColorDark: 'focus:border-green-700',
    focusRingColorLight: 'focus:ring focus:ring-green-200',
    focusRingColorDark: 'focus:ring focus:ring-green-900',
    scaleLoaderColor: '#059669',
  },
  indigo: {
    bgColor: 'bg-indigo-600',
    bgColorLight: 'bg-indigo-500',
    bgColorPale: 'bg-indigo-100',
    hoverBgColorLight: 'hover:bg-indigo-500',
    activeBgColorDark: 'active:bg-indigo-700',
    borderColor: 'border-indigo-600',
    textColor: 'text-indigo-600',
    focusBorderColorDark: 'focus:border-indigo-700',
    focusRingColorLight: 'focus:ring focus:ring-indigo-200',
    focusRingColorDark: 'focus:ring focus:ring-indigo-900',
    scaleLoaderColor: '#4F46E5',
  },
  blue: {
    bgColor: 'bg-blue-600',
    bgColorLight: 'bg-blue-500',
    bgColorPale: 'bg-blue-100',
    hoverBgColorLight: 'hover:bg-blue-500',
    activeBgColorDark: 'active:bg-blue-700',
    borderColor: 'border-blue-600',
    textColor: 'text-blue-600',
    focusBorderColorDark: 'focus:border-blue-700',
    focusRingColorLight: 'focus:ring focus:ring-blue-200',
    focusRingColorDark: 'focus:ring focus:ring-blue-900',
    scaleLoaderColor: '#2563EB',
  },
  purple: {
    bgColor: 'bg-purple-600',
    bgColorLight: 'bg-purple-500',
    bgColorPale: 'bg-purple-100',
    hoverBgColorLight: 'hover:bg-purple-500',
    activeBgColorDark: 'active:bg-purple-700',
    borderColor: 'border-purple-600',
    textColor: 'text-purple-600',
    focusBorderColorDark: 'focus:border-purple-700',
    focusRingColorLight: 'focus:ring focus:ring-purple-200',
    focusRingColorDark: 'focus:ring focus:ring-purple-900',
    scaleLoaderColor: '#7C3AED',
  },
  pink: {
    bgColor: 'bg-pink-600',
    bgColorLight: 'bg-pink-500',
    bgColorPale: 'bg-pink-100',
    hoverBgColorLight: 'hover:bg-pink-500',
    activeBgColorDark: 'active:bg-pink-700',
    borderColor: 'border-pink-600',
    textColor: 'text-pink-600',
    focusBorderColorDark: 'focus:border-pink-700',
    focusRingColorLight: 'focus:ring focus:ring-pink-200',
    focusRingColorDark: 'focus:ring focus:ring-pink-900',
    scaleLoaderColor: '#DB2777',
  },
}
