/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/peer-to-peer-campaign': {
    get: {
      responses: {
        /** @description success */
        200: {
          content: {
            'application/json': components['schemas']['PeerToPeerCampaignResource']
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    PeerToPeerCampaignResource: {
      id: string
      title?: string
      fundraiser_type: string
      team_name: string
      team_join_code: string
      team_join_shortlink_url: string
      team_goal_amount: number
      team_currency_code: string
      team_members: Record<string, never>[]
      goal_amount: number
      currency_code: string
      avatar_name: string
      social_avatar: string
      amount_raised: number | null
      share_links: {
        facebook: string
        twitter: string
        linkedin: string
        sms: string
        email: string
      }
      supporter: {
        id?: string
        id_deprecated?: string
        active?: boolean
        display_name?: string
        first_name?: string
        last_name?: string
        email?: string
        type?: string
        is_organization?: boolean
        email_opt_in?: boolean
        vendor_contract_id?: string | null
        billing_address?: {
          first_name: string
          last_name: string
          company: string | null
          email: string
          address1: string | null
          address2: string | null
          city: string | null
          state: string | null
          zip: string | null
          country: string | null
          phone: string | null
        }
        shipping_address?: {
          first_name: string
          last_name: string
          company: string | null
          email: string
          address1: string | null
          address2: string | null
          city: string | null
          state: string | null
          zip: string | null
          country: string | null
          phone: string | null
        }
        created_at?: string
        updated_at?: string
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export type operations = Record<string, never>
