
name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - '**.php'

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: docker
          MYSQL_DATABASE: sys-backend
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:4.0.14-alpine
        ports:
          - 6379

    steps:

    - name: Cleanup previous runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: pcov
        extensions: bcmath, curl, gd, imagick, intl, json, mbstring, mysql, opcache, readline, redis, soap, sqlite3, xml, zip
        tools: composer:2.1.1

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '410.0.0'
        project_id: 'infrastructure-161602'

    - name: Get composer cache directory
      id: composer-cache-files
      run: echo "directory=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache-files.outputs.directory }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Login to Givecloud Composer
      run: composer config http-basic.givecloud.dev composer ${GC_COMPOSER_PWD}
      env:
        GC_COMPOSER_PWD: ${{ secrets.GC_COMPOSER_PWD }}

    - name: Run composer
      run: |-
        composer install \
          --no-ansi \
          --no-interaction \
          --no-suggest \
          --no-progress \
          --prefer-dist

    - name: Setup env file
      run: |-
        gcloud secrets versions access \
          --secret=TESTING_ENV_FEATURE_AFFINITY latest > .env

    - name: Wait for MySQL service
      env:
        PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done

    - name: Run phpunit
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        GIVECLOUD_DB_0: 127.0.0.1
        GIVECLOUD_DB_1: 127.0.0.1
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
      run: ./vendor/bin/phpunit --no-coverage --coverage-clover clover.xml

    - name: Submit coverage report
      env:
        COVERAGE_SECRET: ${{ secrets.COVERAGE_SECRET }}
      run: ./scripts/php-coverage
